@base_url = http://localhost:7071/api

### Admin: Create Default Platform

POST {{base_url}}/platform/default HTTP/1.1
Content-Type: application/json

{
    "name": "AIRe Development Platform",
    "modules": {
        "id": {
            "type": "id",
            "endpoint": "http://localhost:7072/api",
            "access": "public"
        },
        "memory": {
            "type": "memory",
            "endpoint": "http://localhost:7073/api",
            "access": "public"
        },
        "ai": {
            "type": "ai",
            "endpoint": "http://localhost:7074/api",
            "access": "public"
        }
    }
}
