@base_url = http://localhost:7071/api

### Get platform config

GET {{base_url}}/v1/config HTTP/1.1
Accept: application/json

### Get internal platform config

GET {{base_url}}/v1/config/internal HTTP/1.1
Accept: application/json
Aire-Service-Key: 
